name: die_swiper
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 3.0.2
homepage: https://github.com/etsunnycat-boop/die_swiper
repository: https://github.com/etsunnycat-boop/die_swiper
issue_tracker: https://github.com/etsunnycat-boop/die_swiper/issues

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=0.1.4"

dev_dependencies:
  flutter_lints_plus: ">=2.0.0 <4.0.0"
  flutter_test:
    sdk: flutter

